name: EDT

on:
  schedule:
    - cron: '30 22 * * *'
      timezone: "America/New_York"
      
  workflow_dispatch:
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "Sneha and Angel"
