name: Try a Simple Action

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "GitHub Explorer"
